artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/nikhil-xyz/datasets/raw/main/preprocessed_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train.csv", "test.csv"]


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_ingestion/preprocessed_data/train.csv
  model_path: artifacts/model_trainer/model.pkl
  

model_evaluation:
  root_dir: artifacts/model_evaluation
  train_data_path: artifacts/data_ingestion/preprocessed_data/train.csv
  test_data_path: artifacts/data_ingestion/preprocessed_data/test.csv
  model_path: artifacts/model_trainer/model.pkl
  predictions_path: artifacts/model_evaluation/predictions.csv


  